name: Deploy Github pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-gh-pages:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: deploy
        run: npm run deploy